name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint and enforce score
        run: |
          echo "Running pylint..."
          SCORE=$(pylint app.py | awk '/rated at/ {print $7}' | cut -d'/' -f1)

          echo "Pylint score: $SCORE"

          python -c "import sys; sys.exit(1 if float('$SCORE') < 7.0 else 0)"

  secret-scan:
    name: Secret Scanning with trufflehog
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --results=verified,unknown

  dependency-check:
    name: Dependency Check with Trivy 
    runs-on: ubuntu-latest
    needs: [secret-scan, lint]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install pip-audit
      run: |
        python -m pip install --upgrade pip
        pip install pip-audit

    - name: Scan Python dependencies
      run: pip-audit

    - name: Scan Dockerfile with Trivy
      uses: aquasecurity/trivy-action@v0.20.0
      with:
        scan-type: config
        scan-ref: .
        severity: CRITICAL
        exit-code: '1'